void L1TkTau_Multiplicity()
{
//=========Macro generated from canvas: plots/L1TkTau_Multiplicity/
//=========  (Thu Apr 20 16:00:53 2017) by ROOT version6.07/03
   TCanvas *plots/L1TkTau_Multiplicity = new TCanvas("plots/L1TkTau_Multiplicity", "",1,1,600,576);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   plots/L1TkTau_Multiplicity->SetHighLightColor(2);
   plots/L1TkTau_Multiplicity->Range(-2.829114,-4.742962,11.72785,0.9721317);
   plots/L1TkTau_Multiplicity->SetFillColor(0);
   plots/L1TkTau_Multiplicity->SetBorderMode(0);
   plots/L1TkTau_Multiplicity->SetBorderSize(2);
   plots/L1TkTau_Multiplicity->SetLogy();
   plots/L1TkTau_Multiplicity->SetGridy();
   plots/L1TkTau_Multiplicity->SetTickx(1);
   plots/L1TkTau_Multiplicity->SetTicky(1);
   plots/L1TkTau_Multiplicity->SetLeftMargin(0.16);
   plots/L1TkTau_Multiplicity->SetRightMargin(0.05);
   plots/L1TkTau_Multiplicity->SetTopMargin(0.06);
   plots/L1TkTau_Multiplicity->SetBottomMargin(0.13);
   plots/L1TkTau_Multiplicity->SetFrameFillStyle(0);
   plots/L1TkTau_Multiplicity->SetFrameBorderMode(0);
   plots/L1TkTau_Multiplicity->SetFrameFillStyle(0);
   plots/L1TkTau_Multiplicity->SetFrameBorderMode(0);
   
   TH1F *hframe__5 = new TH1F("hframe__5","",1000,-0.5,11);
   hframe__5->SetMinimum(0.0001);
   hframe__5->SetMaximum(4.2582);
   hframe__5->SetDirectory(0);
   hframe__5->SetStats(0);
   hframe__5->SetLineStyle(0);
   hframe__5->SetMarkerStyle(20);
   hframe__5->GetXaxis()->SetTitle("Multiplicity");
   hframe__5->GetXaxis()->SetLabelFont(43);
   hframe__5->GetXaxis()->SetLabelOffset(0.007);
   hframe__5->GetXaxis()->SetLabelSize(27);
   hframe__5->GetXaxis()->SetTitleSize(33);
   hframe__5->GetXaxis()->SetTitleOffset(0.9);
   hframe__5->GetXaxis()->SetTitleFont(43);
   hframe__5->GetYaxis()->SetTitle("Events / 1");
   hframe__5->GetYaxis()->SetLabelFont(43);
   hframe__5->GetYaxis()->SetLabelOffset(0.007);
   hframe__5->GetYaxis()->SetLabelSize(27);
   hframe__5->GetYaxis()->SetTitleSize(33);
   hframe__5->GetYaxis()->SetTitleOffset(1.25);
   hframe__5->GetYaxis()->SetTitleFont(43);
   hframe__5->GetZaxis()->SetLabelFont(43);
   hframe__5->GetZaxis()->SetLabelOffset(0.007);
   hframe__5->GetZaxis()->SetLabelSize(27);
   hframe__5->GetZaxis()->SetTitleSize(33);
   hframe__5->GetZaxis()->SetTitleFont(43);
   hframe__5->Draw(" ");
   
   TH1D *L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6 = new TH1D("L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6","L1TkTau_Multiplicity",15,-0.5,14.5);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetBinContent(1,0.03715418);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetBinContent(2,0.1531809);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetBinContent(3,0.2772551);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetBinContent(4,0.2689675);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetBinContent(5,0.1617088);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetBinContent(6,0.07042479);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetBinContent(7,0.02354166);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetBinContent(8,0.006085599);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetBinContent(9,0.001281179);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetBinContent(10,0.000240221);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetBinContent(11,0.0001201105);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetBinContent(12,4.003683e-05);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetBinError(1,0.001219646);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetBinError(2,0.002476465);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetBinError(3,0.003331729);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetBinError(4,0.003281555);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetBinError(5,0.002544466);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetBinError(6,0.001679162);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetBinError(7,0.0009708416);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetBinError(8,0.0004936072);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetBinError(9,0.0002264825);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetBinError(10,9.806981e-05);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetBinError(11,6.934583e-05);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetBinError(12,4.003683e-05);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetEntries(24981);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ff0000");
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetLineColor(ci);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetLineStyle(3);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetLineWidth(3);

   ci = TColor::GetColor("#ff0000");
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetMarkerColor(ci);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetMarkerStyle(22);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->SetMarkerSize(1.2);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->GetXaxis()->SetRange(1,30);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->GetXaxis()->SetLabelFont(42);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->GetXaxis()->SetLabelSize(0.035);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->GetXaxis()->SetTitleSize(0.035);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->GetXaxis()->SetTitleFont(42);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->GetYaxis()->SetLabelFont(42);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->GetYaxis()->SetLabelSize(0.035);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->GetYaxis()->SetTitleSize(0.035);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->GetYaxis()->SetTitleFont(42);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->GetZaxis()->SetLabelFont(42);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->GetZaxis()->SetLabelSize(0.035);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->GetZaxis()->SetTitleSize(0.035);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->GetZaxis()->SetTitleFont(42);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned__6->Draw("HIST same");
   
   TH1D *L1TkTau_Multiplicity_MinBias_cloned__7 = new TH1D("L1TkTau_Multiplicity_MinBias_cloned__7","L1TkTau_Multiplicity",15,-0.5,14.5);
   L1TkTau_Multiplicity_MinBias_cloned__7->SetBinContent(1,0.42582);
   L1TkTau_Multiplicity_MinBias_cloned__7->SetBinContent(2,0.34739);
   L1TkTau_Multiplicity_MinBias_cloned__7->SetBinContent(3,0.15643);
   L1TkTau_Multiplicity_MinBias_cloned__7->SetBinContent(4,0.05157);
   L1TkTau_Multiplicity_MinBias_cloned__7->SetBinContent(5,0.0146);
   L1TkTau_Multiplicity_MinBias_cloned__7->SetBinContent(6,0.00327);
   L1TkTau_Multiplicity_MinBias_cloned__7->SetBinContent(7,0.00074);
   L1TkTau_Multiplicity_MinBias_cloned__7->SetBinContent(8,0.00015);
   L1TkTau_Multiplicity_MinBias_cloned__7->SetBinContent(9,3e-05);
   L1TkTau_Multiplicity_MinBias_cloned__7->SetBinError(1,0.002063541);
   L1TkTau_Multiplicity_MinBias_cloned__7->SetBinError(2,0.00186384);
   L1TkTau_Multiplicity_MinBias_cloned__7->SetBinError(3,0.00125072);
   L1TkTau_Multiplicity_MinBias_cloned__7->SetBinError(4,0.0007181226);
   L1TkTau_Multiplicity_MinBias_cloned__7->SetBinError(5,0.0003820995);
   L1TkTau_Multiplicity_MinBias_cloned__7->SetBinError(6,0.0001808314);
   L1TkTau_Multiplicity_MinBias_cloned__7->SetBinError(7,8.602325e-05);
   L1TkTau_Multiplicity_MinBias_cloned__7->SetBinError(8,3.872983e-05);
   L1TkTau_Multiplicity_MinBias_cloned__7->SetBinError(9,1.732051e-05);
   L1TkTau_Multiplicity_MinBias_cloned__7->SetEntries(100004);
   L1TkTau_Multiplicity_MinBias_cloned__7->SetDirectory(0);
   L1TkTau_Multiplicity_MinBias_cloned__7->SetFillColor(1);
   L1TkTau_Multiplicity_MinBias_cloned__7->SetFillStyle(3001);
   L1TkTau_Multiplicity_MinBias_cloned__7->SetLineWidth(3);
   L1TkTau_Multiplicity_MinBias_cloned__7->SetMarkerStyle(20);
   L1TkTau_Multiplicity_MinBias_cloned__7->SetMarkerSize(1.2);
   L1TkTau_Multiplicity_MinBias_cloned__7->GetXaxis()->SetRange(1,30);
   L1TkTau_Multiplicity_MinBias_cloned__7->GetXaxis()->SetLabelFont(42);
   L1TkTau_Multiplicity_MinBias_cloned__7->GetXaxis()->SetLabelSize(0.035);
   L1TkTau_Multiplicity_MinBias_cloned__7->GetXaxis()->SetTitleSize(0.035);
   L1TkTau_Multiplicity_MinBias_cloned__7->GetXaxis()->SetTitleFont(42);
   L1TkTau_Multiplicity_MinBias_cloned__7->GetYaxis()->SetLabelFont(42);
   L1TkTau_Multiplicity_MinBias_cloned__7->GetYaxis()->SetLabelSize(0.035);
   L1TkTau_Multiplicity_MinBias_cloned__7->GetYaxis()->SetTitleSize(0.035);
   L1TkTau_Multiplicity_MinBias_cloned__7->GetYaxis()->SetTitleFont(42);
   L1TkTau_Multiplicity_MinBias_cloned__7->GetZaxis()->SetLabelFont(42);
   L1TkTau_Multiplicity_MinBias_cloned__7->GetZaxis()->SetLabelSize(0.035);
   L1TkTau_Multiplicity_MinBias_cloned__7->GetZaxis()->SetTitleSize(0.035);
   L1TkTau_Multiplicity_MinBias_cloned__7->GetZaxis()->SetTitleFont(42);
   L1TkTau_Multiplicity_MinBias_cloned__7->Draw("HIST same");
   TLine *line = new TLine(0,0.0001,0,4.2582);
   line->SetLineStyle(2);
   line->SetLineWidth(3);
   line->Draw();
   
   TLegend *leg = new TLegend(0.63,0.72,0.83,0.92,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.035);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(4000);
   TLegendEntry *entry=leg->AddEntry("L1TkTau_Multiplicity_MinBias_cloned_forLegend","MB","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("L1TkTau_Multiplicity_VBF_HToTauTau_cloned_forLegend","VBF H^{0}#rightarrow#tau#tau","F");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(3);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   TH1F *hframe_copy__8 = new TH1F("hframe_copy__8","",1000,-0.5,11);
   hframe_copy__8->SetMinimum(0.0001);
   hframe_copy__8->SetMaximum(4.2582);
   hframe_copy__8->SetDirectory(0);
   hframe_copy__8->SetStats(0);
   hframe_copy__8->SetLineStyle(0);
   hframe_copy__8->SetMarkerStyle(20);
   hframe_copy__8->GetXaxis()->SetTitle("Multiplicity");
   hframe_copy__8->GetXaxis()->SetLabelFont(43);
   hframe_copy__8->GetXaxis()->SetLabelOffset(0.007);
   hframe_copy__8->GetXaxis()->SetLabelSize(27);
   hframe_copy__8->GetXaxis()->SetTitleSize(33);
   hframe_copy__8->GetXaxis()->SetTitleOffset(0.9);
   hframe_copy__8->GetXaxis()->SetTitleFont(43);
   hframe_copy__8->GetYaxis()->SetTitle("Events / 1");
   hframe_copy__8->GetYaxis()->SetLabelFont(43);
   hframe_copy__8->GetYaxis()->SetLabelOffset(0.007);
   hframe_copy__8->GetYaxis()->SetLabelSize(27);
   hframe_copy__8->GetYaxis()->SetTitleSize(33);
   hframe_copy__8->GetYaxis()->SetTitleOffset(1.25);
   hframe_copy__8->GetYaxis()->SetTitleFont(43);
   hframe_copy__8->GetZaxis()->SetLabelFont(43);
   hframe_copy__8->GetZaxis()->SetLabelOffset(0.007);
   hframe_copy__8->GetZaxis()->SetLabelSize(27);
   hframe_copy__8->GetZaxis()->SetTitleSize(33);
   hframe_copy__8->GetZaxis()->SetTitleFont(43);
   hframe_copy__8->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.95,0.952,"PU=140, 14 TeV");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.952,"CMS");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(30);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2706,0.952,"Phase-2 Simulation");
tex->SetNDC();
   tex->SetTextFont(53);
   tex->SetTextSize(22.8);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.18,0.92,"");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(17);
   tex->SetLineWidth(2);
   tex->Draw();
   plots/L1TkTau_Multiplicity->Modified();
   plots/L1TkTau_Multiplicity->cd();
   plots/L1TkTau_Multiplicity->SetSelected(plots/L1TkTau_Multiplicity);
}
