void L1TkTau_IsoTks_d0Sig()
{
//=========Macro generated from canvas: plots/L1TkTau_IsoTks_d0Sig/
//=========  (Thu Apr 20 18:40:57 2017) by ROOT version6.07/03
   TCanvas *plots/L1TkTau_IsoTks_d0Sig = new TCanvas("plots/L1TkTau_IsoTks_d0Sig", "",1,1,600,576);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   plots/L1TkTau_IsoTks_d0Sig->SetHighLightColor(2);
   plots/L1TkTau_IsoTks_d0Sig->Range(-7.025316,-4.802469,5.632911,1.37037);
   plots/L1TkTau_IsoTks_d0Sig->SetFillColor(0);
   plots/L1TkTau_IsoTks_d0Sig->SetBorderMode(0);
   plots/L1TkTau_IsoTks_d0Sig->SetBorderSize(2);
   plots/L1TkTau_IsoTks_d0Sig->SetLogy();
   plots/L1TkTau_IsoTks_d0Sig->SetGridy();
   plots/L1TkTau_IsoTks_d0Sig->SetTickx(1);
   plots/L1TkTau_IsoTks_d0Sig->SetTicky(1);
   plots/L1TkTau_IsoTks_d0Sig->SetLeftMargin(0.16);
   plots/L1TkTau_IsoTks_d0Sig->SetRightMargin(0.05);
   plots/L1TkTau_IsoTks_d0Sig->SetTopMargin(0.06);
   plots/L1TkTau_IsoTks_d0Sig->SetBottomMargin(0.13);
   plots/L1TkTau_IsoTks_d0Sig->SetFrameFillStyle(0);
   plots/L1TkTau_IsoTks_d0Sig->SetFrameBorderMode(0);
   plots/L1TkTau_IsoTks_d0Sig->SetFrameFillStyle(0);
   plots/L1TkTau_IsoTks_d0Sig->SetFrameBorderMode(0);
   
   TH1F *hframe__69 = new TH1F("hframe__69","",1000,-5,5);
   hframe__69->SetMinimum(0.0001);
   hframe__69->SetMaximum(10);
   hframe__69->SetDirectory(0);
   hframe__69->SetStats(0);
   hframe__69->SetLineStyle(0);
   hframe__69->SetMarkerStyle(20);
   hframe__69->GetXaxis()->SetTitle("d_{0}/#sigma(d_{0})");
   hframe__69->GetXaxis()->SetLabelFont(43);
   hframe__69->GetXaxis()->SetLabelOffset(0.007);
   hframe__69->GetXaxis()->SetLabelSize(27);
   hframe__69->GetXaxis()->SetTitleSize(33);
   hframe__69->GetXaxis()->SetTitleOffset(0.9);
   hframe__69->GetXaxis()->SetTitleFont(43);
   hframe__69->GetYaxis()->SetTitle("Arbitrary Units / 0.01");
   hframe__69->GetYaxis()->SetLabelFont(43);
   hframe__69->GetYaxis()->SetLabelOffset(0.007);
   hframe__69->GetYaxis()->SetLabelSize(27);
   hframe__69->GetYaxis()->SetTitleSize(33);
   hframe__69->GetYaxis()->SetTitleOffset(1.25);
   hframe__69->GetYaxis()->SetTitleFont(43);
   hframe__69->GetZaxis()->SetLabelFont(43);
   hframe__69->GetZaxis()->SetLabelOffset(0.007);
   hframe__69->GetZaxis()->SetLabelSize(27);
   hframe__69->GetZaxis()->SetTitleSize(33);
   hframe__69->GetZaxis()->SetTitleFont(43);
   hframe__69->Draw(" ");
   
   TH1D *L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70 = new TH1D("L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70","L1TkTau_IsoTks_d0Sig",4000,-20,20);
   L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70->SetBinContent(1901,1);
   L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70->SetBinError(1901,0.006224401);
   L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70->SetEntries(25815);
   L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ff0000");
   L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70->SetLineColor(ci);
   L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70->SetLineStyle(3);
   L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70->SetLineWidth(3);

   ci = TColor::GetColor("#ff0000");
   L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70->SetMarkerColor(ci);
   L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70->SetMarkerStyle(22);
   L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70->SetMarkerSize(1.2);
   L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70->GetXaxis()->SetRange(1,4000);
   L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70->GetXaxis()->SetLabelFont(42);
   L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70->GetXaxis()->SetLabelSize(0.035);
   L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70->GetXaxis()->SetTitleSize(0.035);
   L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70->GetXaxis()->SetTitleFont(42);
   L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70->GetYaxis()->SetLabelFont(42);
   L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70->GetYaxis()->SetLabelSize(0.035);
   L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70->GetYaxis()->SetTitleSize(0.035);
   L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70->GetYaxis()->SetTitleFont(42);
   L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70->GetZaxis()->SetLabelFont(42);
   L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70->GetZaxis()->SetLabelSize(0.035);
   L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70->GetZaxis()->SetTitleSize(0.035);
   L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70->GetZaxis()->SetTitleFont(42);
   L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned__70->Draw("HIST same");
   
   TH1D *L1TkTau_IsoTks_d0Sig_MinBias_cloned__71 = new TH1D("L1TkTau_IsoTks_d0Sig_MinBias_cloned__71","L1TkTau_IsoTks_d0Sig",4000,-20,20);
   L1TkTau_IsoTks_d0Sig_MinBias_cloned__71->SetBinContent(1901,1);
   L1TkTau_IsoTks_d0Sig_MinBias_cloned__71->SetBinError(1901,0.002793688);
   L1TkTau_IsoTks_d0Sig_MinBias_cloned__71->SetEntries(128132);
   L1TkTau_IsoTks_d0Sig_MinBias_cloned__71->SetDirectory(0);
   L1TkTau_IsoTks_d0Sig_MinBias_cloned__71->SetFillColor(1);
   L1TkTau_IsoTks_d0Sig_MinBias_cloned__71->SetFillStyle(3001);
   L1TkTau_IsoTks_d0Sig_MinBias_cloned__71->SetLineWidth(3);
   L1TkTau_IsoTks_d0Sig_MinBias_cloned__71->SetMarkerStyle(20);
   L1TkTau_IsoTks_d0Sig_MinBias_cloned__71->SetMarkerSize(1.2);
   L1TkTau_IsoTks_d0Sig_MinBias_cloned__71->GetXaxis()->SetRange(1,4000);
   L1TkTau_IsoTks_d0Sig_MinBias_cloned__71->GetXaxis()->SetLabelFont(42);
   L1TkTau_IsoTks_d0Sig_MinBias_cloned__71->GetXaxis()->SetLabelSize(0.035);
   L1TkTau_IsoTks_d0Sig_MinBias_cloned__71->GetXaxis()->SetTitleSize(0.035);
   L1TkTau_IsoTks_d0Sig_MinBias_cloned__71->GetXaxis()->SetTitleFont(42);
   L1TkTau_IsoTks_d0Sig_MinBias_cloned__71->GetYaxis()->SetLabelFont(42);
   L1TkTau_IsoTks_d0Sig_MinBias_cloned__71->GetYaxis()->SetLabelSize(0.035);
   L1TkTau_IsoTks_d0Sig_MinBias_cloned__71->GetYaxis()->SetTitleSize(0.035);
   L1TkTau_IsoTks_d0Sig_MinBias_cloned__71->GetYaxis()->SetTitleFont(42);
   L1TkTau_IsoTks_d0Sig_MinBias_cloned__71->GetZaxis()->SetLabelFont(42);
   L1TkTau_IsoTks_d0Sig_MinBias_cloned__71->GetZaxis()->SetLabelSize(0.035);
   L1TkTau_IsoTks_d0Sig_MinBias_cloned__71->GetZaxis()->SetTitleSize(0.035);
   L1TkTau_IsoTks_d0Sig_MinBias_cloned__71->GetZaxis()->SetTitleFont(42);
   L1TkTau_IsoTks_d0Sig_MinBias_cloned__71->Draw("HIST same");
   TLine *line = new TLine(0,0.0001,0,10);
   line->SetLineStyle(2);
   line->SetLineWidth(3);
   line->Draw();
   
   TLegend *leg = new TLegend(0.71,0.82,0.91,0.92,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.035);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(4000);
   TLegendEntry *entry=leg->AddEntry("L1TkTau_IsoTks_d0Sig_MinBias_cloned_forLegend","MB","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("L1TkTau_IsoTks_d0Sig_VBF_HToTauTau_cloned_forLegend","VBF H^{0}#rightarrow#tau#tau","F");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(3);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   TH1F *hframe_copy__72 = new TH1F("hframe_copy__72","",1000,-5,5);
   hframe_copy__72->SetMinimum(0.0001);
   hframe_copy__72->SetMaximum(10);
   hframe_copy__72->SetDirectory(0);
   hframe_copy__72->SetStats(0);
   hframe_copy__72->SetLineStyle(0);
   hframe_copy__72->SetMarkerStyle(20);
   hframe_copy__72->GetXaxis()->SetTitle("d_{0}/#sigma(d_{0})");
   hframe_copy__72->GetXaxis()->SetLabelFont(43);
   hframe_copy__72->GetXaxis()->SetLabelOffset(0.007);
   hframe_copy__72->GetXaxis()->SetLabelSize(27);
   hframe_copy__72->GetXaxis()->SetTitleSize(33);
   hframe_copy__72->GetXaxis()->SetTitleOffset(0.9);
   hframe_copy__72->GetXaxis()->SetTitleFont(43);
   hframe_copy__72->GetYaxis()->SetTitle("Arbitrary Units / 0.01");
   hframe_copy__72->GetYaxis()->SetLabelFont(43);
   hframe_copy__72->GetYaxis()->SetLabelOffset(0.007);
   hframe_copy__72->GetYaxis()->SetLabelSize(27);
   hframe_copy__72->GetYaxis()->SetTitleSize(33);
   hframe_copy__72->GetYaxis()->SetTitleOffset(1.25);
   hframe_copy__72->GetYaxis()->SetTitleFont(43);
   hframe_copy__72->GetZaxis()->SetLabelFont(43);
   hframe_copy__72->GetZaxis()->SetLabelOffset(0.007);
   hframe_copy__72->GetZaxis()->SetLabelSize(27);
   hframe_copy__72->GetZaxis()->SetTitleSize(33);
   hframe_copy__72->GetZaxis()->SetTitleFont(43);
   hframe_copy__72->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.95,0.952,"PU=140, 14 TeV");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.952,"CMS");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(30);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2706,0.952,"Phase-2 Simulation");
tex->SetNDC();
   tex->SetTextFont(53);
   tex->SetTextSize(22.8);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.18,0.92,"");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(17);
   tex->SetLineWidth(2);
   tex->Draw();
   plots/L1TkTau_IsoTks_d0Sig->Modified();
   plots/L1TkTau_IsoTks_d0Sig->cd();
   plots/L1TkTau_IsoTks_d0Sig->SetSelected(plots/L1TkTau_IsoTks_d0Sig);
}
