void L1TkTau_IsoTks_d0SigAbs()
{
//=========Macro generated from canvas: plots/L1TkTau_IsoTks_d0SigAbs/
//=========  (Thu Apr 20 18:40:57 2017) by ROOT version6.07/03
   TCanvas *plots/L1TkTau_IsoTks_d0SigAbs = new TCanvas("plots/L1TkTau_IsoTks_d0SigAbs", "",1,1,600,576);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   plots/L1TkTau_IsoTks_d0SigAbs->SetHighLightColor(2);
   plots/L1TkTau_IsoTks_d0SigAbs->Range(-1.012658,-4.802469,5.316456,1.37037);
   plots/L1TkTau_IsoTks_d0SigAbs->SetFillColor(0);
   plots/L1TkTau_IsoTks_d0SigAbs->SetBorderMode(0);
   plots/L1TkTau_IsoTks_d0SigAbs->SetBorderSize(2);
   plots/L1TkTau_IsoTks_d0SigAbs->SetLogy();
   plots/L1TkTau_IsoTks_d0SigAbs->SetGridy();
   plots/L1TkTau_IsoTks_d0SigAbs->SetTickx(1);
   plots/L1TkTau_IsoTks_d0SigAbs->SetTicky(1);
   plots/L1TkTau_IsoTks_d0SigAbs->SetLeftMargin(0.16);
   plots/L1TkTau_IsoTks_d0SigAbs->SetRightMargin(0.05);
   plots/L1TkTau_IsoTks_d0SigAbs->SetTopMargin(0.06);
   plots/L1TkTau_IsoTks_d0SigAbs->SetBottomMargin(0.13);
   plots/L1TkTau_IsoTks_d0SigAbs->SetFrameFillStyle(0);
   plots/L1TkTau_IsoTks_d0SigAbs->SetFrameBorderMode(0);
   plots/L1TkTau_IsoTks_d0SigAbs->SetFrameFillStyle(0);
   plots/L1TkTau_IsoTks_d0SigAbs->SetFrameBorderMode(0);
   
   TH1F *hframe__77 = new TH1F("hframe__77","",1000,0,5);
   hframe__77->SetMinimum(0.0001);
   hframe__77->SetMaximum(10);
   hframe__77->SetDirectory(0);
   hframe__77->SetStats(0);
   hframe__77->SetLineStyle(0);
   hframe__77->SetMarkerStyle(20);
   hframe__77->GetXaxis()->SetTitle("|d_{0}/#sigma(d_{0})|");
   hframe__77->GetXaxis()->SetLabelFont(43);
   hframe__77->GetXaxis()->SetLabelOffset(0.007);
   hframe__77->GetXaxis()->SetLabelSize(27);
   hframe__77->GetXaxis()->SetTitleSize(33);
   hframe__77->GetXaxis()->SetTitleOffset(0.9);
   hframe__77->GetXaxis()->SetTitleFont(43);
   hframe__77->GetYaxis()->SetTitle("Arbitrary Units / 0.01");
   hframe__77->GetYaxis()->SetLabelFont(43);
   hframe__77->GetYaxis()->SetLabelOffset(0.007);
   hframe__77->GetYaxis()->SetLabelSize(27);
   hframe__77->GetYaxis()->SetTitleSize(33);
   hframe__77->GetYaxis()->SetTitleOffset(1.25);
   hframe__77->GetYaxis()->SetTitleFont(43);
   hframe__77->GetZaxis()->SetLabelFont(43);
   hframe__77->GetZaxis()->SetLabelOffset(0.007);
   hframe__77->GetZaxis()->SetLabelSize(27);
   hframe__77->GetZaxis()->SetTitleSize(33);
   hframe__77->GetZaxis()->SetTitleFont(43);
   hframe__77->Draw(" ");
   
   TH1D *L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78 = new TH1D("L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78","L1TkTau_IsoTks_d0SigAbs",2000,0,20);
   L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78->SetBinContent(1,1);
   L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78->SetBinError(1,0.006224401);
   L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78->SetEntries(25815);
   L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ff0000");
   L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78->SetLineColor(ci);
   L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78->SetLineStyle(3);
   L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78->SetLineWidth(3);

   ci = TColor::GetColor("#ff0000");
   L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78->SetMarkerColor(ci);
   L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78->SetMarkerStyle(22);
   L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78->SetMarkerSize(1.2);
   L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78->GetXaxis()->SetRange(1,2000);
   L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78->GetXaxis()->SetLabelFont(42);
   L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78->GetXaxis()->SetLabelSize(0.035);
   L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78->GetXaxis()->SetTitleSize(0.035);
   L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78->GetXaxis()->SetTitleFont(42);
   L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78->GetYaxis()->SetLabelFont(42);
   L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78->GetYaxis()->SetLabelSize(0.035);
   L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78->GetYaxis()->SetTitleSize(0.035);
   L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78->GetYaxis()->SetTitleFont(42);
   L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78->GetZaxis()->SetLabelFont(42);
   L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78->GetZaxis()->SetLabelSize(0.035);
   L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78->GetZaxis()->SetTitleSize(0.035);
   L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78->GetZaxis()->SetTitleFont(42);
   L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned__78->Draw("HIST same");
   
   TH1D *L1TkTau_IsoTks_d0SigAbs_MinBias_cloned__79 = new TH1D("L1TkTau_IsoTks_d0SigAbs_MinBias_cloned__79","L1TkTau_IsoTks_d0SigAbs",2000,0,20);
   L1TkTau_IsoTks_d0SigAbs_MinBias_cloned__79->SetBinContent(1,1);
   L1TkTau_IsoTks_d0SigAbs_MinBias_cloned__79->SetBinError(1,0.002793688);
   L1TkTau_IsoTks_d0SigAbs_MinBias_cloned__79->SetEntries(128132);
   L1TkTau_IsoTks_d0SigAbs_MinBias_cloned__79->SetDirectory(0);
   L1TkTau_IsoTks_d0SigAbs_MinBias_cloned__79->SetFillColor(1);
   L1TkTau_IsoTks_d0SigAbs_MinBias_cloned__79->SetFillStyle(3001);
   L1TkTau_IsoTks_d0SigAbs_MinBias_cloned__79->SetLineWidth(3);
   L1TkTau_IsoTks_d0SigAbs_MinBias_cloned__79->SetMarkerStyle(20);
   L1TkTau_IsoTks_d0SigAbs_MinBias_cloned__79->SetMarkerSize(1.2);
   L1TkTau_IsoTks_d0SigAbs_MinBias_cloned__79->GetXaxis()->SetRange(1,2000);
   L1TkTau_IsoTks_d0SigAbs_MinBias_cloned__79->GetXaxis()->SetLabelFont(42);
   L1TkTau_IsoTks_d0SigAbs_MinBias_cloned__79->GetXaxis()->SetLabelSize(0.035);
   L1TkTau_IsoTks_d0SigAbs_MinBias_cloned__79->GetXaxis()->SetTitleSize(0.035);
   L1TkTau_IsoTks_d0SigAbs_MinBias_cloned__79->GetXaxis()->SetTitleFont(42);
   L1TkTau_IsoTks_d0SigAbs_MinBias_cloned__79->GetYaxis()->SetLabelFont(42);
   L1TkTau_IsoTks_d0SigAbs_MinBias_cloned__79->GetYaxis()->SetLabelSize(0.035);
   L1TkTau_IsoTks_d0SigAbs_MinBias_cloned__79->GetYaxis()->SetTitleSize(0.035);
   L1TkTau_IsoTks_d0SigAbs_MinBias_cloned__79->GetYaxis()->SetTitleFont(42);
   L1TkTau_IsoTks_d0SigAbs_MinBias_cloned__79->GetZaxis()->SetLabelFont(42);
   L1TkTau_IsoTks_d0SigAbs_MinBias_cloned__79->GetZaxis()->SetLabelSize(0.035);
   L1TkTau_IsoTks_d0SigAbs_MinBias_cloned__79->GetZaxis()->SetTitleSize(0.035);
   L1TkTau_IsoTks_d0SigAbs_MinBias_cloned__79->GetZaxis()->SetTitleFont(42);
   L1TkTau_IsoTks_d0SigAbs_MinBias_cloned__79->Draw("HIST same");
   
   TLegend *leg = new TLegend(0.71,0.82,0.91,0.92,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.035);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(4000);
   TLegendEntry *entry=leg->AddEntry("L1TkTau_IsoTks_d0SigAbs_MinBias_cloned_forLegend","MB","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("L1TkTau_IsoTks_d0SigAbs_VBF_HToTauTau_cloned_forLegend","VBF H^{0}#rightarrow#tau#tau","F");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(3);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   TH1F *hframe_copy__80 = new TH1F("hframe_copy__80","",1000,0,5);
   hframe_copy__80->SetMinimum(0.0001);
   hframe_copy__80->SetMaximum(10);
   hframe_copy__80->SetDirectory(0);
   hframe_copy__80->SetStats(0);
   hframe_copy__80->SetLineStyle(0);
   hframe_copy__80->SetMarkerStyle(20);
   hframe_copy__80->GetXaxis()->SetTitle("|d_{0}/#sigma(d_{0})|");
   hframe_copy__80->GetXaxis()->SetLabelFont(43);
   hframe_copy__80->GetXaxis()->SetLabelOffset(0.007);
   hframe_copy__80->GetXaxis()->SetLabelSize(27);
   hframe_copy__80->GetXaxis()->SetTitleSize(33);
   hframe_copy__80->GetXaxis()->SetTitleOffset(0.9);
   hframe_copy__80->GetXaxis()->SetTitleFont(43);
   hframe_copy__80->GetYaxis()->SetTitle("Arbitrary Units / 0.01");
   hframe_copy__80->GetYaxis()->SetLabelFont(43);
   hframe_copy__80->GetYaxis()->SetLabelOffset(0.007);
   hframe_copy__80->GetYaxis()->SetLabelSize(27);
   hframe_copy__80->GetYaxis()->SetTitleSize(33);
   hframe_copy__80->GetYaxis()->SetTitleOffset(1.25);
   hframe_copy__80->GetYaxis()->SetTitleFont(43);
   hframe_copy__80->GetZaxis()->SetLabelFont(43);
   hframe_copy__80->GetZaxis()->SetLabelOffset(0.007);
   hframe_copy__80->GetZaxis()->SetLabelSize(27);
   hframe_copy__80->GetZaxis()->SetTitleSize(33);
   hframe_copy__80->GetZaxis()->SetTitleFont(43);
   hframe_copy__80->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.95,0.952,"PU=140, 14 TeV");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.952,"CMS");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(30);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2706,0.952,"Phase-2 Simulation");
tex->SetNDC();
   tex->SetTextFont(53);
   tex->SetTextSize(22.8);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.18,0.92,"");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(17);
   tex->SetLineWidth(2);
   tex->Draw();
   plots/L1TkTau_IsoTks_d0SigAbs->Modified();
   plots/L1TkTau_IsoTks_d0SigAbs->cd();
   plots/L1TkTau_IsoTks_d0SigAbs->SetSelected(plots/L1TkTau_IsoTks_d0SigAbs);
}
