void L1TkTau_NIsoTks()
{
//=========Macro generated from canvas: plots/L1TkTau_NIsoTks/
//=========  (Mon May 22 18:36:22 2017) by ROOT version6.08/06
   TCanvas *plots/L1TkTau_NIsoTks = new TCanvas("plots/L1TkTau_NIsoTks", "",1,1,600,576);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   plots/L1TkTau_NIsoTks->SetHighLightColor(2);
   plots/L1TkTau_NIsoTks->Range(-2.829114,-2.481481,11.72785,1.222222);
   plots/L1TkTau_NIsoTks->SetFillColor(0);
   plots/L1TkTau_NIsoTks->SetBorderMode(0);
   plots/L1TkTau_NIsoTks->SetBorderSize(2);
   plots/L1TkTau_NIsoTks->SetLogy();
   plots/L1TkTau_NIsoTks->SetGridx();
   plots/L1TkTau_NIsoTks->SetGridy();
   plots/L1TkTau_NIsoTks->SetTickx(1);
   plots/L1TkTau_NIsoTks->SetTicky(1);
   plots/L1TkTau_NIsoTks->SetLeftMargin(0.16);
   plots/L1TkTau_NIsoTks->SetRightMargin(0.05);
   plots/L1TkTau_NIsoTks->SetTopMargin(0.06);
   plots/L1TkTau_NIsoTks->SetBottomMargin(0.13);
   plots/L1TkTau_NIsoTks->SetFrameFillStyle(0);
   plots/L1TkTau_NIsoTks->SetFrameBorderMode(0);
   plots/L1TkTau_NIsoTks->SetFrameFillStyle(0);
   plots/L1TkTau_NIsoTks->SetFrameBorderMode(0);
   
   TH1F *hframe__5 = new TH1F("hframe__5","",1000,-0.5,11);
   hframe__5->SetMinimum(1e-05);
   hframe__5->SetMaximum(0);
   hframe__5->SetDirectory(0);
   hframe__5->SetStats(0);
   hframe__5->SetLineStyle(0);
   hframe__5->SetMarkerStyle(20);
   hframe__5->GetXaxis()->SetTitle("multiplicity");
   hframe__5->GetXaxis()->SetLabelFont(43);
   hframe__5->GetXaxis()->SetLabelOffset(0.007);
   hframe__5->GetXaxis()->SetLabelSize(27);
   hframe__5->GetXaxis()->SetTitleSize(33);
   hframe__5->GetXaxis()->SetTitleOffset(0.9);
   hframe__5->GetXaxis()->SetTitleFont(43);
   hframe__5->GetYaxis()->SetTitle("Arbitrary Units / 1");
   hframe__5->GetYaxis()->SetLabelFont(43);
   hframe__5->GetYaxis()->SetLabelOffset(0.007);
   hframe__5->GetYaxis()->SetLabelSize(27);
   hframe__5->GetYaxis()->SetTitleSize(33);
   hframe__5->GetYaxis()->SetTitleOffset(1.25);
   hframe__5->GetYaxis()->SetTitleFont(43);
   hframe__5->GetZaxis()->SetLabelFont(43);
   hframe__5->GetZaxis()->SetLabelOffset(0.007);
   hframe__5->GetZaxis()->SetLabelSize(27);
   hframe__5->GetZaxis()->SetTitleSize(33);
   hframe__5->GetZaxis()->SetTitleFont(43);
   hframe__5->Draw(" ");
   
   TH1D *L1TkTau_NIsoTks_SingleTau_PU140_cloned__6 = new TH1D("L1TkTau_NIsoTks_SingleTau_PU140_cloned__6","",15,-0.5,14.5);
   L1TkTau_NIsoTks_SingleTau_PU140_cloned__6->SetEntries(4);
   L1TkTau_NIsoTks_SingleTau_PU140_cloned__6->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#cc3333");
   L1TkTau_NIsoTks_SingleTau_PU140_cloned__6->SetFillColor(ci);
   L1TkTau_NIsoTks_SingleTau_PU140_cloned__6->SetFillStyle(3001);

   ci = TColor::GetColor("#cc3333");
   L1TkTau_NIsoTks_SingleTau_PU140_cloned__6->SetLineColor(ci);
   L1TkTau_NIsoTks_SingleTau_PU140_cloned__6->SetLineStyle(3);
   L1TkTau_NIsoTks_SingleTau_PU140_cloned__6->SetLineWidth(3);

   ci = TColor::GetColor("#cc3333");
   L1TkTau_NIsoTks_SingleTau_PU140_cloned__6->SetMarkerColor(ci);
   L1TkTau_NIsoTks_SingleTau_PU140_cloned__6->SetMarkerStyle(20);
   L1TkTau_NIsoTks_SingleTau_PU140_cloned__6->SetMarkerSize(1.3);
   L1TkTau_NIsoTks_SingleTau_PU140_cloned__6->GetXaxis()->SetRange(1,15);
   L1TkTau_NIsoTks_SingleTau_PU140_cloned__6->GetXaxis()->SetLabelFont(42);
   L1TkTau_NIsoTks_SingleTau_PU140_cloned__6->GetXaxis()->SetLabelSize(0.035);
   L1TkTau_NIsoTks_SingleTau_PU140_cloned__6->GetXaxis()->SetTitleSize(0.035);
   L1TkTau_NIsoTks_SingleTau_PU140_cloned__6->GetXaxis()->SetTitleFont(42);
   L1TkTau_NIsoTks_SingleTau_PU140_cloned__6->GetYaxis()->SetLabelFont(42);
   L1TkTau_NIsoTks_SingleTau_PU140_cloned__6->GetYaxis()->SetLabelSize(0.035);
   L1TkTau_NIsoTks_SingleTau_PU140_cloned__6->GetYaxis()->SetTitleSize(0.035);
   L1TkTau_NIsoTks_SingleTau_PU140_cloned__6->GetYaxis()->SetTitleFont(42);
   L1TkTau_NIsoTks_SingleTau_PU140_cloned__6->GetZaxis()->SetLabelFont(42);
   L1TkTau_NIsoTks_SingleTau_PU140_cloned__6->GetZaxis()->SetLabelSize(0.035);
   L1TkTau_NIsoTks_SingleTau_PU140_cloned__6->GetZaxis()->SetTitleSize(0.035);
   L1TkTau_NIsoTks_SingleTau_PU140_cloned__6->GetZaxis()->SetTitleFont(42);
   L1TkTau_NIsoTks_SingleTau_PU140_cloned__6->Draw("AP same");
   
   TH1D *L1TkTau_NIsoTks_SingleNeutrino_PU140_cloned__7 = new TH1D("L1TkTau_NIsoTks_SingleNeutrino_PU140_cloned__7","",15,-0.5,14.5);
   L1TkTau_NIsoTks_SingleNeutrino_PU140_cloned__7->SetEntries(4);
   L1TkTau_NIsoTks_SingleNeutrino_PU140_cloned__7->SetDirectory(0);
   L1TkTau_NIsoTks_SingleNeutrino_PU140_cloned__7->SetFillColor(1);
   L1TkTau_NIsoTks_SingleNeutrino_PU140_cloned__7->SetFillStyle(3001);
   L1TkTau_NIsoTks_SingleNeutrino_PU140_cloned__7->SetLineWidth(3);
   L1TkTau_NIsoTks_SingleNeutrino_PU140_cloned__7->SetMarkerStyle(20);
   L1TkTau_NIsoTks_SingleNeutrino_PU140_cloned__7->SetMarkerSize(1.2);
   L1TkTau_NIsoTks_SingleNeutrino_PU140_cloned__7->GetXaxis()->SetRange(1,15);
   L1TkTau_NIsoTks_SingleNeutrino_PU140_cloned__7->GetXaxis()->SetLabelFont(42);
   L1TkTau_NIsoTks_SingleNeutrino_PU140_cloned__7->GetXaxis()->SetLabelSize(0.035);
   L1TkTau_NIsoTks_SingleNeutrino_PU140_cloned__7->GetXaxis()->SetTitleSize(0.035);
   L1TkTau_NIsoTks_SingleNeutrino_PU140_cloned__7->GetXaxis()->SetTitleFont(42);
   L1TkTau_NIsoTks_SingleNeutrino_PU140_cloned__7->GetYaxis()->SetLabelFont(42);
   L1TkTau_NIsoTks_SingleNeutrino_PU140_cloned__7->GetYaxis()->SetLabelSize(0.035);
   L1TkTau_NIsoTks_SingleNeutrino_PU140_cloned__7->GetYaxis()->SetTitleSize(0.035);
   L1TkTau_NIsoTks_SingleNeutrino_PU140_cloned__7->GetYaxis()->SetTitleFont(42);
   L1TkTau_NIsoTks_SingleNeutrino_PU140_cloned__7->GetZaxis()->SetLabelFont(42);
   L1TkTau_NIsoTks_SingleNeutrino_PU140_cloned__7->GetZaxis()->SetLabelSize(0.035);
   L1TkTau_NIsoTks_SingleNeutrino_PU140_cloned__7->GetZaxis()->SetTitleSize(0.035);
   L1TkTau_NIsoTks_SingleNeutrino_PU140_cloned__7->GetZaxis()->SetTitleFont(42);
   L1TkTau_NIsoTks_SingleNeutrino_PU140_cloned__7->Draw("HIST same");
   TLine *line = new TLine(0,1e-05,0,0);
   line->SetLineStyle(2);
   line->SetLineWidth(3);
   line->Draw();
   
   TLegend *leg = new TLegend(0.6,0.77,0.8,0.92,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.035);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(4000);
   TLegendEntry *entry=leg->AddEntry("L1TkTau_NIsoTks_SingleNeutrino_PU140_cloned","MB (PU=140)","LF");
   entry->SetFillColor(1);
   entry->SetFillStyle(3001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("L1TkTau_NIsoTks_SingleTau_PU140_cloned","Single #tau (PU=140)","AP");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#cc3333");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.3);
   entry->SetTextFont(62);
   leg->Draw();
   
   TH1F *hframe_copy__8 = new TH1F("hframe_copy__8","",1000,-0.5,11);
   hframe_copy__8->SetMinimum(1e-05);
   hframe_copy__8->SetMaximum(0);
   hframe_copy__8->SetDirectory(0);
   hframe_copy__8->SetStats(0);
   hframe_copy__8->SetLineStyle(0);
   hframe_copy__8->SetMarkerStyle(20);
   hframe_copy__8->GetXaxis()->SetTitle("multiplicity");
   hframe_copy__8->GetXaxis()->SetLabelFont(43);
   hframe_copy__8->GetXaxis()->SetLabelOffset(0.007);
   hframe_copy__8->GetXaxis()->SetLabelSize(27);
   hframe_copy__8->GetXaxis()->SetTitleSize(33);
   hframe_copy__8->GetXaxis()->SetTitleOffset(0.9);
   hframe_copy__8->GetXaxis()->SetTitleFont(43);
   hframe_copy__8->GetYaxis()->SetTitle("Arbitrary Units / 1");
   hframe_copy__8->GetYaxis()->SetLabelFont(43);
   hframe_copy__8->GetYaxis()->SetLabelOffset(0.007);
   hframe_copy__8->GetYaxis()->SetLabelSize(27);
   hframe_copy__8->GetYaxis()->SetTitleSize(33);
   hframe_copy__8->GetYaxis()->SetTitleOffset(1.25);
   hframe_copy__8->GetYaxis()->SetTitleFont(43);
   hframe_copy__8->GetZaxis()->SetLabelFont(43);
   hframe_copy__8->GetZaxis()->SetLabelOffset(0.007);
   hframe_copy__8->GetZaxis()->SetLabelSize(27);
   hframe_copy__8->GetZaxis()->SetTitleSize(33);
   hframe_copy__8->GetZaxis()->SetTitleFont(43);
   hframe_copy__8->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.95,0.952,"14 TeV");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.952,"CMS");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(30);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2706,0.952,"Phase-2 Simulation");
tex->SetNDC();
   tex->SetTextFont(53);
   tex->SetTextSize(22.8);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.18,0.92,"");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(17);
   tex->SetLineWidth(2);
   tex->Draw();
   plots/L1TkTau_NIsoTks->Modified();
   plots/L1TkTau_NIsoTks->cd();
   plots/L1TkTau_NIsoTks->SetSelected(plots/L1TkTau_NIsoTks);
}
