void L1TkTau_Multiplicity()
{
//=========Macro generated from canvas: plots/L1TkTau_Multiplicity/
//=========  (Wed May  3 13:07:26 2017) by ROOT version6.07/03
   TCanvas *plots/L1TkTau_Multiplicity = new TCanvas("plots/L1TkTau_Multiplicity", "",1,1,677,576);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   plots/L1TkTau_Multiplicity->SetHighLightColor(2);
   plots/L1TkTau_Multiplicity->Range(-3.287879,-4.757969,14.13636,1.072565);
   plots/L1TkTau_Multiplicity->SetFillColor(0);
   plots/L1TkTau_Multiplicity->SetBorderMode(0);
   plots/L1TkTau_Multiplicity->SetBorderSize(2);
   plots/L1TkTau_Multiplicity->SetLogy();
   plots/L1TkTau_Multiplicity->SetGridy();
   plots/L1TkTau_Multiplicity->SetTickx(1);
   plots/L1TkTau_Multiplicity->SetTicky(1);
   plots/L1TkTau_Multiplicity->SetLeftMargin(0.16);
   plots/L1TkTau_Multiplicity->SetRightMargin(0.18);
   plots/L1TkTau_Multiplicity->SetTopMargin(0.06);
   plots/L1TkTau_Multiplicity->SetBottomMargin(0.13);
   plots/L1TkTau_Multiplicity->SetFrameFillStyle(0);
   plots/L1TkTau_Multiplicity->SetFrameBorderMode(0);
   plots/L1TkTau_Multiplicity->SetFrameFillStyle(0);
   plots/L1TkTau_Multiplicity->SetFrameBorderMode(0);
   
   TH1F *hframe__3 = new TH1F("hframe__3","",1000,-0.5,11);
   hframe__3->SetMinimum(0.0001);
   hframe__3->SetMaximum(5.2812);
   hframe__3->SetDirectory(0);
   hframe__3->SetStats(0);
   hframe__3->SetLineStyle(0);
   hframe__3->SetMarkerStyle(20);
   hframe__3->GetXaxis()->SetTitle("Multiplicity");
   hframe__3->GetXaxis()->SetLabelFont(43);
   hframe__3->GetXaxis()->SetLabelOffset(0.007);
   hframe__3->GetXaxis()->SetLabelSize(27);
   hframe__3->GetXaxis()->SetTitleSize(33);
   hframe__3->GetXaxis()->SetTitleOffset(0.9);
   hframe__3->GetXaxis()->SetTitleFont(43);
   hframe__3->GetYaxis()->SetTitle("Arbitrary Units / 1");
   hframe__3->GetYaxis()->SetLabelFont(43);
   hframe__3->GetYaxis()->SetLabelOffset(0.007);
   hframe__3->GetYaxis()->SetLabelSize(27);
   hframe__3->GetYaxis()->SetTitleSize(33);
   hframe__3->GetYaxis()->SetTitleOffset(1.25);
   hframe__3->GetYaxis()->SetTitleFont(43);
   hframe__3->GetZaxis()->SetLabelFont(43);
   hframe__3->GetZaxis()->SetLabelOffset(0.007);
   hframe__3->GetZaxis()->SetLabelSize(27);
   hframe__3->GetZaxis()->SetTitleSize(33);
   hframe__3->GetZaxis()->SetTitleFont(43);
   hframe__3->Draw(" ");
   
   TH1D *L1TkTau_Multiplicity_VBF_HToTauTau_cloned = new TH1D("L1TkTau_Multiplicity_VBF_HToTauTau_cloned","",15,-0.5,14.5);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetBinContent(1,0.0553309);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetBinContent(2,0.1993034);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetBinContent(3,0.3058013);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetBinContent(4,0.2515114);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetBinContent(5,0.1256756);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetBinContent(6,0.04592225);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetBinContent(7,0.01333227);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetBinContent(8,0.002362173);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetBinContent(9,0.0006005525);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetBinContent(10,0.0001201105);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetBinContent(12,4.003683e-05);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetBinError(1,0.00148838);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetBinError(2,0.002824797);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetBinError(3,0.003499045);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetBinError(4,0.003173282);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetBinError(5,0.002243135);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetBinError(6,0.001355943);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetBinError(7,0.0007306037);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetBinError(8,0.0003075288);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetBinError(9,0.000155062);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetBinError(10,6.934583e-05);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetBinError(12,4.003683e-05);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetEntries(24981);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ff0000");
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetLineColor(ci);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetLineStyle(3);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetLineWidth(3);

   ci = TColor::GetColor("#ff0000");
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetMarkerColor(ci);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetMarkerStyle(22);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->SetMarkerSize(1.2);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->GetXaxis()->SetRange(1,30);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->GetXaxis()->SetLabelFont(42);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->GetXaxis()->SetLabelSize(0.035);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->GetXaxis()->SetTitleSize(0.035);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->GetXaxis()->SetTitleFont(42);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->GetYaxis()->SetLabelFont(42);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->GetYaxis()->SetLabelSize(0.035);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->GetYaxis()->SetTitleSize(0.035);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->GetYaxis()->SetTitleFont(42);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->GetZaxis()->SetLabelFont(42);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->GetZaxis()->SetLabelSize(0.035);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->GetZaxis()->SetTitleSize(0.035);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->GetZaxis()->SetTitleFont(42);
   L1TkTau_Multiplicity_VBF_HToTauTau_cloned->Draw("COLZ same");
   
   TH1D *L1TkTau_Multiplicity_MinBias_cloned = new TH1D("L1TkTau_Multiplicity_MinBias_cloned","",15,-0.5,14.5);
   L1TkTau_Multiplicity_MinBias_cloned->SetBinContent(1,0.52812);
   L1TkTau_Multiplicity_MinBias_cloned->SetBinContent(2,0.32117);
   L1TkTau_Multiplicity_MinBias_cloned->SetBinContent(3,0.11283);
   L1TkTau_Multiplicity_MinBias_cloned->SetBinContent(4,0.02972);
   L1TkTau_Multiplicity_MinBias_cloned->SetBinContent(5,0.0067);
   L1TkTau_Multiplicity_MinBias_cloned->SetBinContent(6,0.00108);
   L1TkTau_Multiplicity_MinBias_cloned->SetBinContent(7,0.00028);
   L1TkTau_Multiplicity_MinBias_cloned->SetBinContent(8,9e-05);
   L1TkTau_Multiplicity_MinBias_cloned->SetBinContent(9,1e-05);
   L1TkTau_Multiplicity_MinBias_cloned->SetBinError(1,0.002298086);
   L1TkTau_Multiplicity_MinBias_cloned->SetBinError(2,0.001792122);
   L1TkTau_Multiplicity_MinBias_cloned->SetBinError(3,0.001062215);
   L1TkTau_Multiplicity_MinBias_cloned->SetBinError(4,0.0005451605);
   L1TkTau_Multiplicity_MinBias_cloned->SetBinError(5,0.0002588436);
   L1TkTau_Multiplicity_MinBias_cloned->SetBinError(6,0.000103923);
   L1TkTau_Multiplicity_MinBias_cloned->SetBinError(7,5.291503e-05);
   L1TkTau_Multiplicity_MinBias_cloned->SetBinError(8,3e-05);
   L1TkTau_Multiplicity_MinBias_cloned->SetBinError(9,1e-05);
   L1TkTau_Multiplicity_MinBias_cloned->SetEntries(100004);
   L1TkTau_Multiplicity_MinBias_cloned->SetDirectory(0);
   L1TkTau_Multiplicity_MinBias_cloned->SetFillColor(1);
   L1TkTau_Multiplicity_MinBias_cloned->SetFillStyle(3001);
   L1TkTau_Multiplicity_MinBias_cloned->SetLineWidth(3);
   L1TkTau_Multiplicity_MinBias_cloned->SetMarkerStyle(20);
   L1TkTau_Multiplicity_MinBias_cloned->SetMarkerSize(1.2);
   L1TkTau_Multiplicity_MinBias_cloned->GetXaxis()->SetRange(1,30);
   L1TkTau_Multiplicity_MinBias_cloned->GetXaxis()->SetLabelFont(42);
   L1TkTau_Multiplicity_MinBias_cloned->GetXaxis()->SetLabelSize(0.035);
   L1TkTau_Multiplicity_MinBias_cloned->GetXaxis()->SetTitleSize(0.035);
   L1TkTau_Multiplicity_MinBias_cloned->GetXaxis()->SetTitleFont(42);
   L1TkTau_Multiplicity_MinBias_cloned->GetYaxis()->SetLabelFont(42);
   L1TkTau_Multiplicity_MinBias_cloned->GetYaxis()->SetLabelSize(0.035);
   L1TkTau_Multiplicity_MinBias_cloned->GetYaxis()->SetTitleSize(0.035);
   L1TkTau_Multiplicity_MinBias_cloned->GetYaxis()->SetTitleFont(42);
   L1TkTau_Multiplicity_MinBias_cloned->GetZaxis()->SetLabelFont(42);
   L1TkTau_Multiplicity_MinBias_cloned->GetZaxis()->SetLabelSize(0.035);
   L1TkTau_Multiplicity_MinBias_cloned->GetZaxis()->SetTitleSize(0.035);
   L1TkTau_Multiplicity_MinBias_cloned->GetZaxis()->SetTitleFont(42);
   L1TkTau_Multiplicity_MinBias_cloned->Draw("COLZ same");
   TLine *line = new TLine(0,0.0001,0,5.2812);
   line->SetLineStyle(2);
   line->SetLineWidth(3);
   line->Draw();
   
   TLegend *leg = new TLegend(0.71,0.82,0.91,0.92,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.035);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(4000);
   TLegendEntry *entry=leg->AddEntry("L1TkTau_Multiplicity_MinBias_cloned_forLegend","MB","F");
   entry->SetFillColor(1);
   entry->SetFillStyle(3001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   entry=leg->AddEntry("L1TkTau_Multiplicity_VBF_HToTauTau_cloned_forLegend","VBF H^{0}#rightarrow#tau#tau","F");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(3);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(62);
   leg->Draw();
   
   TH1F *hframe_copy__4 = new TH1F("hframe_copy__4","",1000,-0.5,11);
   hframe_copy__4->SetMinimum(0.0001);
   hframe_copy__4->SetMaximum(5.2812);
   hframe_copy__4->SetDirectory(0);
   hframe_copy__4->SetStats(0);
   hframe_copy__4->SetLineStyle(0);
   hframe_copy__4->SetMarkerStyle(20);
   hframe_copy__4->GetXaxis()->SetTitle("Multiplicity");
   hframe_copy__4->GetXaxis()->SetLabelFont(43);
   hframe_copy__4->GetXaxis()->SetLabelOffset(0.007);
   hframe_copy__4->GetXaxis()->SetLabelSize(27);
   hframe_copy__4->GetXaxis()->SetTitleSize(33);
   hframe_copy__4->GetXaxis()->SetTitleOffset(0.9);
   hframe_copy__4->GetXaxis()->SetTitleFont(43);
   hframe_copy__4->GetYaxis()->SetTitle("Arbitrary Units / 1");
   hframe_copy__4->GetYaxis()->SetLabelFont(43);
   hframe_copy__4->GetYaxis()->SetLabelOffset(0.007);
   hframe_copy__4->GetYaxis()->SetLabelSize(27);
   hframe_copy__4->GetYaxis()->SetTitleSize(33);
   hframe_copy__4->GetYaxis()->SetTitleOffset(1.25);
   hframe_copy__4->GetYaxis()->SetTitleFont(43);
   hframe_copy__4->GetZaxis()->SetLabelFont(43);
   hframe_copy__4->GetZaxis()->SetLabelOffset(0.007);
   hframe_copy__4->GetZaxis()->SetLabelSize(27);
   hframe_copy__4->GetZaxis()->SetTitleSize(33);
   hframe_copy__4->GetZaxis()->SetTitleFont(43);
   hframe_copy__4->Draw("sameaxis");
   TLatex *   tex = new TLatex(0.82,0.952,"PU=140, 14 TeV");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(43);
   tex->SetTextSize(24);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.952,"CMS");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(30);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2524,0.952,"Phase-2 Simulation");
tex->SetNDC();
   tex->SetTextFont(53);
   tex->SetTextSize(22.8);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.18,0.92,"");
tex->SetNDC();
   tex->SetTextFont(63);
   tex->SetTextSize(17);
   tex->SetLineWidth(2);
   tex->Draw();
   plots/L1TkTau_Multiplicity->Modified();
   plots/L1TkTau_Multiplicity->cd();
   plots/L1TkTau_Multiplicity->SetSelected(plots/L1TkTau_Multiplicity);
}
